name = "rhel-9.2-microshift-4.13"
description = "RHEL 9.2 with MicroShift 4.13 installed."
version = "0.0.2"
modules = []
groups = []
distro = "rhel-92"

[[packages]]
name = "microshift"
version = "4.13*"

[[packages]]
name = "microshift-greenboot"
version = "4.13*"

[[packages]]
name = "microshift-networking"
version = "4.13*"

[[packages]]
name = "microshift-selinux"
version = "4.13*"

[[packages]]
name = "git"
version = "*"

[[packages]]
name = "iputils"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "iotop"
version = "*"

[[packages]]
name = "redhat-release"
version = "*"

[[packages]]
name = "cockpit"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[customizations.services]
enabled = ["crio", "microshift", "cockpit.socket"]

[customizations.firewall]
ports = ["22:tcp", "80:tcp", "443:tcp", "5353:udp", "6443:tcp", "30000-32767:tcp", "30000-32767:udp"]

[customizations.firewall.services]
enabled = ["mdns", "ssh", "http", "https"]

[[customizations.firewall.zones]]
name = "trusted"
sources = ["10.42.0.0/16", "169.254.169.1"]
