name = "rhel-9.2"
description = "Basic RHEL 9.2 edge image without MicroShift."
version = "0.0.1"
distro = "rhel-92"
modules = []
groups = []

[customizations.firewall]
ports = ["22:tcp"]

[customizations.firewall.services]
enabled = ["ssh"]
